[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (configure these in Netlify UI)
# VITE_API_URL = "https://your-backend-api.vercel.app"
